### ISSUE TITLE
Error in vim: "Unknown function: nvim_buf_add_highlight"

### ISSUE THREAD

**Issue by ipkiss42** [autozimu/LanguageClient-neovim#1018]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? N/A
- Did you check [troubleshooting]? Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

When running `:call LanguageClient#textDocument_documentHighlight()` (either manually or via an autocommand) in Vim 8.2, I get the following error:

```
[LC] Error: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "\'Vim(let):E117: Unknown function: nvim_buf_add_highlight\'", data: None }, id: Num(42) }
```
From the name, it looks like a nvim-specific function which should not be called in Vim. 

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 26 2020 11:23:21)
Included patches: 1-510                                                                        
Compiled by Arch Linux                                                                         
Huge version with GTK3 GUI.  Features included (+) or not (-):    
```
- This plugin version (`git rev-parse --short HEAD`): `18434f2`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.157`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): Not needed
- Language server link and version: rust-analyzer, but I don't think it's server-specific.

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

I'm sure you will manage :) Let me know if not.

**Comment by martskins** [comment]
I see where the issue is. The correct thing to do would be to delegate the vim/neovim function call to a function of our own where we clear the previous highlights (if any) and set the new ones. The setting part is `matchaddpos` in vim and `nvim_buf_add_highlight` in neovim. The clearing is the one I don't know in vim, I'll investigate on that, but if anyone knows the answer to it please ping me.

**Comment by martskins** [comment]
(Sorry clicked wrong button)

**Comment by iddinev** [comment]
Any update on the issue ?? Looking at the vim help - the clearing of 'matchaddpos' is done with 'clearmatches' or with 'matchdelete(id)' for a single, specific match (id is obtained by 'getmatches').

**Comment by martskins** [comment]
I have something in the works, but the highlight code is spread all over the place so it might take a while for me to finish this and validate it's working correctly. If someone wants to give it a go I'm happy to try and help.

**Comment by iddinev** [comment]
I'm pretty new to the whole LSP thing (I still can't configure the servers to work as intended with the LanguageClient on vim 8.2) so I'd probably be of even less help :(

**Comment by martskins** [comment]
@iddinev @ipkiss42  Opened #1123 which I believe should fix this. If any of you are able to test it out it would be great.

---

As for the difficulty you're having with configuring the servers @iddinev, if you want to open an issue I can give you a hand there, and we can probably update the readme after that to make it clearer.

**Comment by iddinev** [comment]
@martskins I'll first replicate my config on neovim, because I am still not sure whether the problems I'm having are because of: LanguageClient configs, LS configs, vim configs or me missing some LSP knowledge.

**Comment by martskins** [comment]
Closing via #1123

**Comment by iddinev** [comment]
Ok, I've played around with LC and have a bit more  clarification on my part, but I still have some stuff that are unclear to me.
If not specified - I'm asking for both nvim and vim.

**Q1** - Is there a way to configure LC to show the full text, or is this a design issue ?
I'm only asking because in some cases the hover text that get for some symbol is wildly different from the one that LC got in the 'handle*' method. For example - if I hover that stdout, from the example below, I get a oneliner help text.
When using the [palantir/python-lc](https://github.com/palantir/python-language-server) and get the additional completion info from deoplete, LC logs a 'languageClient/handleCompleteDone' (when I chose a particular option from the menu) method which has the full documentation text that it got from the server and the abbreviated version (read: cut after a couple of lines) it passes to deoplete and I see on my screen:
![Screenshot_2020-11-05_22-09-14](https://user-images.githubusercontent.com/11410938/98299142-e2402000-1fbf-11eb-9363-3edd5f2ede0c.png)
![Screenshot_2020-11-05_23-05-09](https://user-images.githubusercontent.com/11410938/98299152-e5d3a700-1fbf-11eb-8534-946ad550ae65.png)

**Q2** - Is there a way to get the additional completion info/hover text syntax highlighted ?
[Sample from github.com/iamcco/vim-language-server](https://user-images.githubusercontent.com/5492542/81494066-5aab7a00-92d8-11ea-9ccd-31bd6440e622.gif) (sample gif is, I think, produced with coc.vim)
Or am I missing some pluggins/have wrong nvim/vim configs on my part.

**Comment by martskins** [comment]
I'll answer these here but if you could open an issue it would be great, so we keep it on topic and other people can find it easily.

Q1. I opened a draft PR for this a while ago, but it only works in neovim. It's terribly outdated now, and I didn't merge it because it requires neovim 0.5, but I'll try to find another way to implement that, there surely is a way around that for both vim and neovim.

Q2. Theoretically you should get syntax highlighting in your floating windows if you include something like `plasticboy/vim-markdown` in your vim plugins. You can also set `set conceallevel=2` for markdown files if you want it to display like rendered markdown. But I have been experiencing a weird issue with that in that it only shows the proper highlighting once I move into the floating window. Until I do that, all code is shown in green inside the hover window. Spent a while trying to investigate that these past few days but haven't found anything yet, but I'll continue that investigation and see if I can spot the problem. Also, not sure if it's only me or if everyone else is seeing the same issue.

**Comment by martskins** [comment]
@iddinev You can try the PR for Q1 in #1043

**Comment by iddinev** [comment]
@martskins The hover highlighting doesn't seem to work in vim8. The stuff you mentioned in your answer to **Q2** kinda does the trick for neovim, but in vim8 I am still seeing:

>\`\`\`python
><some_doc_text>
>\`\`\`

Maybe for some reason the hover window doesn't get its filetype properly set to 'markdown' for the markdown plugins to pick it up?
Also, I noticed in the logs that LC has some logic of deciding (or is getting this info straight from the server) what the hover text type should be, I think I saw that in some cases LC was prepending/appending the 

>\`\`\`python \`\`\``

stuff itself.

I'd think that it would be cool if there would be a way to set the hover/completion extra info filetypes depending on the code file opened, as for example, in python although the LS might send the info listed as plaintext/markdown most of these texts are usually taken from the module's doc strings and is 'valid' python syntax. 
Alas - I am maybe asking too much though..

P.S. If these discussions are to continue I'd suggest some other communication channel as not to spam this issue anymore.
