### ISSUE TITLE
Importing does not work in Java

### ISSUE THREAD

**Issue by tepf** [autozimu/LanguageClient-neovim#158]
Importing does not work in Java projects. `:call LanguageClient_textDocument_codeAction()` shows the option to import but then it fails with the error message `No delegateCommandHandler for java.apply.workspaceEdit`.

There seems to be an issue about this in the [jdt repository](https://github.com/eclipse/eclipse.jdt.ls/issues/376)

Ultimately auto import functionality would be nice of course.

**Comment by autozimu** [comment]
TODO: handle https://github.com/redhat-developer/vscode-java/blob/977973499608ccd5e64115876b250c5dae062023/src/commands.ts#L60 within this plugin.

**Comment by autozimu** [comment]
I pushed a commit trying to resolve this issue. But I cannot get jdt show code actions locally thus I cannot verify if it will actually resolve this. Please report back if it doesn't.

**Comment by tepf** [comment]
Nothing changed for me. It's still the same error message. Here are the steps I used.

1. Create new project: `mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`
2. Add `Scanner sc = new Scanner(System.in);` to `myapp/src/main/java/com/mycompany/app/App.java` main method.
3. Go back with cursor to Scanner and run: `:call LanguageClient_textDocument_codeAction()`

**Comment by tepf** [comment]
It seems to work now! However the imports are appended like this:

    import A; import B, ...

instead of

    import A;
    import B;

**Comment by autozimu** [comment]
Yes, I've also noticed that. Don't have enough time last night to figure it out.

**Comment by tepf** [comment]
It still doesn't seem to work completely. See this example. `Socket` and `PrintWriter` are already imported. What's left to import is `PrintStream`. Executing `codeAction` on `PrintStream` will give me `import java.io.Writer`first (for some reason) then `import PrintStream`. The problem is that only the first/bottom entry can be selected which is `Writer`.

```
package app;

import java.io.PrintWriter;
import java.net.Socket;

public class App {

        public static void main(String[] args) {
                Socket sock = null;
                PrintWriter out = new PrintWriter(new PrintStream(sock.getOutputStream()));
    }
}
```

**Comment by tepf** [comment]
This seems to have fixed the last problem.
