### ISSUE TITLE
"int object is not iterable" in deoplete source since 'next' branch

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#210]
Since switching to the `next` branch, I am constantly receiving error messages from deoplete in the following form:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/languitar/.local/share/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 59, in completion_begin
[deoplete]     self.gather_results(context), context['input'])
[deoplete]   File "/home/languitar/.local/share/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 185, in merge_results
[deoplete]     async_candidates)
[deoplete] TypeError: 'int' object is not iterable
[deoplete] Error while gathering completions.  Use :messages for error details.
```

@Shougo suspected that this is from the language client source, though it is not visible in the stracktrace. Unfortunately, I was not able to reproduce this in a minimal setup.

**Comment by Shougo** [comment]
@languitar Please disable LanguageClient-neovim and check if it is reproduced.

**Comment by languitar** [comment]
Doesn't appear without the language client source. Strangely, I cannot reproduce this with a minimal vimrc.

**Comment by Shougo** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/next/rplugin/python3/deoplete/sources/LanguageClientSource.py#L5

Hm.
The variable may have the invalid value.  If the client is errored.

**Comment by languitar** [comment]
I will add some debugging...

**Comment by languitar** [comment]
There is a 0 in that variable when the error appears. I could patch the source to ignore such cases, but maybe finding the origin is a better approach.

**Comment by languitar** [comment]
Alright, and this seems to happen when the language server crashes:

```
2017-12-13 11:07:07,066 UTC - ERROR - pyls.server - Language server exiting due to uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 34, in handle
    data = self._read_message()
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 91, in _read_message
    raise EOFError()
EOFError
```

**Comment by languitar** [comment]
I have reported this at the language server project: https://github.com/palantir/python-language-server/issues/203. However, after a short look at their implementation, it looks like the client is sending truncated messages to the server.

**Comment by autozimu** [comment]
Were you able to provide debug log? As I cannot reproduce the described issue locally.

**Comment by languitar** [comment]
[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1571083/LanguageClient.log)
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1571084/LanguageServer.log)

There you go. After the update yesterday I don't get a single completion at all. The server immediately dies.

**Comment by autozimu** [comment]
Could you follow issue template to fill out necessary information so that I can try reproduce it?

**Comment by languitar** [comment]
Things got even stranger today after updating to the latest release. Now, LanguageServer.log is always completely empty, warnings from the language server appear with an offset of one line, and the language client wastes more than 200% CPU constantly. I have not seen these issues with a minimal vimrc, but the original crashes of the server are still there, though not that severe.

- neovim/vim version: 0.2.2
- Plugin version (git SHA): 6d0e9538ea81a002d884533bb4fb1a13c2a7948e
- Minimal vimrc:

```
set nocompatible
set hidden

set runtimepath+=~/.local/share/nvim/bundle/deoplete.nvim
set runtimepath+=~/.local/share/nvim/bundle/LanguageClient-neovim

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ }
let g:LanguageClient_autoStart = 1
```

- Language server name/link and version: https://github.com/palantir/python-language-server, 0.12.0
- Reproduction steps: randomly edit in the document. completions are often missing in deoplete and at some point in time you will find the EOFErrors in the server log.

**Comment by autozimu** [comment]
You could clear log files before reproduction, and then upload the log files.

**Comment by autozimu** [comment]
Try use a different logging level.

```
:call LanguageClient_setLoggingLevel('INFO')
```

**Comment by autozimu** [comment]
Should be fixed in https://github.com/autozimu/LanguageClient-neovim/commit/489ec656cc53a3d2121c6ffea12f85874b83075c

**Comment by languitar** [comment]
But i think the actual issue was still that the connection to the language server broke down. Isn't this just preventing what appears at the surface while down there things are still wrong? My impression is that the server shouldn't receive closed stdins.
